# Multiple Linear Regression with sklearn - Exercise Solution

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

## Load the data

In [2]:
data = pd.read_csv("real_estate_price_size_year.csv")

In [3]:
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

## Create the regression

### Declare the dependent and the independent variables

In [4]:
x = data[["size", "year"]]
y = data["price"]

### Regression

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [6]:
reg.intercept_

-5772267.017463278

### Find the coefficients

In [7]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [8]:
reg.score(x,y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [9]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

In [10]:
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.77187171612825

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [12]:
reg.predict([[750,2009]])

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [13]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [21]:
p_values = f_regression(x,y)[1]
p_values
p_values.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [22]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357